#!/bin/bash

#  Copyright 2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

NODE1=localhost
NODE2=dolphin1.client.zytolabor.ch

export LVM_LV=${1:-test}
export LVM_VG=${LVM_VG:-orca}
export LVM_FS=${LVM_FS:-ext3}
export LVM_SIZE=${LVM_SIZE:-4G}


# Main
# ====

clu-disk create $1
ssh $NODE2 clu-disk create $1
