#!/bin/bash

#  Copyright 2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#  Copyright 2008 ZytoLabor <info@zyto-labor.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Commands
# ========
function usage() {
	echo "Usage: $(basename $0) add <hostname>"
	echo

	exit 0
}

function get_master() {
	master_line=$(egrep "^[[:space:]]*master=" /etc/clu-tools/cluster.conf)
	eval "$master_line; echo \$master"
}

function add() {
local node=$1

	ssh $node clu-init init $(get_master)
}

# Main
# ====
if [ $# == 0 ] ; then
	ACTION=usage
else
	ACTION=$1
	shift
fi

$ACTION $@
