#!/bin/bash

#  Copyright 2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Main
# ====

echo "Host:"
echo
uname -a
echo
free
echo

echo "Network:"
ip -family inet address
echo
ip route
echo
if [ -n "$(which brctl)" ] ; then
	brctl show
	echo
else
	echo "No network bridge"
	echo
fi

echo "Disks:"
if [ -n "$(which vgdisplay)" ] ; then
	vgdisplay
	echo
	lvdisplay
	echo
else
	echo "No LVM"
	echo
fi

if [ -f /proc/drbd ] ; then
	cat /proc/drbd
	echo
else
	echo "No DRBD"
	echo
fi

echo "Xen:"
if [ -n "$(which xm)" ] ; then
	xm uptime
	echo

	xm list
else
	echo "No Xen"
	echo
fi
