#!/bin/bash

#  Copyright 2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#  Copyright 2008 ZytoLabor <info@zyto-labor.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Commands
# ========
function usage() {
	echo "Usage: $(basename $0) init [<master>]"
	echo

	exit 0
}

function master() {
local master=${1:-$(hostname -f)}

	echo "master=\"$master\"" >/etc/clu-tools/cluster.conf
}

function init() {
local master=${1:-$(hostname -f)}

	mkdir /etc/clu-tools
	master $master
}

# Main
# ====
if [ $# == 0 ] ; then
	ACTION=init
else
	ACTION=$1
	shift
fi

$ACTION $@

