#!/bin/bash

#  Copyright 2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Commands
# ========
function usage() {
	echo "Usage: $(basename $0)"
	echo

	exit 0
}

function init() {
	mkdir /etc/clu-tools
	echo "primary=$(hostname -f)" >/etc/clu-tools/cluster.conf
}

# Main
# ====
ACTION=${1:init}

$ACTION $@

